server:
  port: 8086
  
spring:
  application:
    name: scoreservice # 服务名必须与Nacos中的配置名对应
  config: 
    import: optional:nacos:scoreservice.yml?refreshEnabled=true


  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848 # Nacos地址
        file-extension: yml
        name: scoreservice 
        refresh-enabled: true